#ifndef _TEXTLIST_H
#define _TEXTLIST_H

/*
 *	Simple double linked list of text generated by the compiler
 */

/* We actually keep this as a ring with a dummy head node */
typedef struct TextList {
    struct TextList *prev;
    struct TextList *next;
    struct TextList *stack;
    char str[0];
} TextList;

extern void TextListAppendAfter(TextList *head, const char *text);
extern void TextListAppend(TextList *head, const char *text);
extern void TextListRemoveRange(TextList *last, TextList *tail);
extern void TextListRemoveTail(TextList *head, TextList *last);
extern void TextListSplice(TextList *at, TextList *start, TextList *end);

/* We actually expose it as these which belong in a different header
   FIXME: */

extern void AppendCode(const char *txt);
extern void PrintCode(void);
extern void PushCode(void);
extern void PopCode(void);
extern void AppendROData(const char *txt);
extern void PrintROData(void);
extern void AppendData(const char *txt);
extern void PrintData(void);
extern void AppendBSS(const char *txt);
extern void PrintBSS(void);
extern void AppendABS(const char *txt);
extern void PrintABS(void);
#endif
