#
#	Build 6502 version of the tools
#
all: as6502 ld6502 nm6502 osize6502 dumprelocs6502

HDR = as.h ld.h obj.h

AOBJ = as0.o as1-6502.o as2.o as3.o as4.o as6-6502.o

CFLAGS = -DTARGET_6502 -Wall -pedantic

as6502: $(HDR) $(AOBJ)
	cc -o as6502 $(AOBJ)

ld6502: $(HDR) ld.o
	cc -o ld6502 ld.o

nm6502: $(HDR) nm.o
	cc -o nm6502 nm.o

osize6502: $(HDR) osize.o
	cc -o osize6502 osize.o

dumprelocs6502: $(HDR) dumprelocs.o
	cc -o dumprelocs6502 dumprelocs.o

clean:
	rm -f *.o *~
	rm -f nm6502 ld6502 as6502 osize6502 dumprelocs6502

install:
	cp nm6502 ld6502 as6502 osize6502 dumprelocs6502 /opt/cc6502/bin/
