#
#	Build 8060 version of the tools
#
all: as8060 ld8060 nm8060 osize8060 dumprelocs8060

HDR = as.h ld.h obj.h

AOBJ = as0.o as1-scmp.o as2.o as3.o as4.o as6-scmp.o

CFLAGS = -DTARGET_SCMP -Wall -pedantic

as8060: $(HDR) $(AOBJ)
	cc -o as8060 $(AOBJ)

ld8060: $(HDR) ld.o
	cc -o ld8060 ld.o

nm8060: $(HDR) nm.o
	cc -o nm8060 nm.o

osize8060: $(HDR) osize.o
	cc -o osize8060 osize.o

dumprelocs8060: $(HDR) dumprelocs.o
	cc -o dumprelocs8060 dumprelocs.o

clean:
	rm -f *.o *~
	rm -f nm8060 ld8060 as8060 osize8060 dumprelocs8060

install:
	cp nm8060 ld8060 as8060 osize8060 dumprelocs8060 /opt/as8060/bin/
